### ISSUE TITLE
Custom "xs" screen overlaps other screens

### ISSUE THREAD

**Issue by Markkop** [jorenvanhee/tailwindcss-debug-screens#21]
Hey, Joren! Great plugin, thanks!
I just added a "xs" resolution to tailwind.config.js and now the debug tool displays all screens as "xs"

```
      screens: {
        xs: '420px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1350px',
        '2xl': '1536px',
        '3xl': '1920px',
      },
```

If I remove the xs line, it works just fine.
Any ideas?

**Comment by Markkop** [comment]
Actually, just tried it on the playground and it worked as usual.
https://play.tailwindcss.com/RhSj3aGmns?file=config

I will debug it a bit more and let you know once I have more info

**Comment by Markkop** [comment]
It turns out that my screen config is on the "extend" field directly.
https://play.tailwindcss.com/2SGZCkXHr5?file=config

With the config above you can reproduce the issue by removing and adding the line with the "xs" screen.

**Comment by jorenvanhee** [comment]
Thanks for the link to the playground @Markkop.

In the plugin I loop over all the `screens` that are defined, in the order they were defined at. I think that causes the issue.

Before extending the screens, the following screens are already defined by tailwind:

```
sm
md
lg
xl
2xl
```

Then you extend the screens. Unknown screens are added to the end of the list, known ones are updated.

```
sm  <-- updated
md  <-- updated
lg. <-- updated
2xl <-- updated
xs  <-- added
```

Since `xs` is at the end of the list, this media query will always be active and overrule the other ones. I would suggest you to not extend the screens but overwrite them.

We could in theory order that list from small to large in the plugin, but then people working with `max-width` media queries instead of `min-width` will have issues.

**Comment by KenTandrian** [comment]
Hi @jorenvanhee, thanks for updating the plugin!

With the release of Tailwind CSS v4, I don't think overriding screens is working anymore. Now we are using `--breakpoint-*` CSS variables to define the screens, and even if we override the default breakpoints by using `--breakpoint-*: initial;`, the media queries are not ordered as expected.

**Comment by jorenvanhee** [comment]
Thanks @KenTandrian for reporting this.

Could you make a new issue for this (since it's only for tailwind v4) with a minimal reproduction of your issue? That would be really helpful.
