### ISSUE TITLE
Make default position in Right Bottom instead Left Bottom

### ISSUE THREAD

**Issue by lamualfa** [jorenvanhee/tailwindcss-debug-screens#4]
## Problem

The problem is when you hover an anchor element that linked to a link, debug screen label will be covered by the Browser default label information.

### Before Hover

![image](https://user-images.githubusercontent.com/39755201/97507690-4eaf9380-19b0-11eb-8581-b028d37f2f87.png)

### After Hover

![image](https://user-images.githubusercontent.com/39755201/97507719-62f39080-19b0-11eb-879f-0c86a8222bac.png)

**Comment by timkley** [comment]
I would go further and suggest the default position to be top left. 

The debug bars of most frameworks (Laravel, Symfony) are positioned on the bottom left or right. And don't get me started on cookie consents 😅

**Comment by jorenvanhee** [comment]
It doesn't bother me personally because I'm mostly busy resizing my window when I look at the debug label. But I definitely get your point.

@timkley I don't really like the top as a default, since it would be covering navigation elements. I also want the default to be subtle. That's maybe the reason why all debug bars are at the bottom 😅 .

In the end, every default position might give a problem for some people. That's why it's configurable. But I was thinking about maybe adding a "center" position. And maybe `["bottom", "center"]` would be a better default.

**Comment by jorenvanhee** [comment]
I'll close this since it can be configured easily.
